const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const brandList = [
    'AQUAZZURA',
    'AGL',
    'ADIDAS',
    'ANTONIO BIAGGI',
    'ATTIZZARE',
    'AZZUR',
    'ALDO BRUE',
    'AURA',
    'ANDREA VENTURA',
    'ALEXANDR MQUEEN',
    'AMINA MUADDI',
    'A&A Nushina',
    'ANGELO RUFFO',
    'ARIGATO',
    'ADIDAS boost',
    'ASICS',
    'ALBERTO CICCIOLI',
    'a.TESTONI',
    'ALEXANDRWANG',
    'ADIDAS BOOST',
    'ALAIA',
    'ANNA LUCCI',
    'ARKET',
    'ASH',
    'ANGELS',
    'AMI',
    'ANTONIO GELO',
    'BURBERRY',
    'BALDININI',
    'BRUNELLO CUCINELLI',
    'BOTTEGA VENETA',
    'BALLY',
    'BUGATTI',
    'BALENCIAGA',
    'BALMAIN',
    'BIKKEMBERGS',
    'BLUMARINE',
    'BARRETT',
    'BOGNER',
    'BRASKA',
    'BOTTICELLI',
    'BILLIONAIRE',
    'BASCONI',
    'BOSCA',
    'BRUNOMAGLI',
    'Babe pay pls',
    'BONTONI',
    'BOOHOO',
    'BETSY',
    'BERLUTI',
    'BARKER',
    'BRAVOMODA',
    'BERSHKA',
    'BLU BARRETT',
    'Brioni',
    'Brunate',
    'BOSS VICTOR',
    'BERISSTINI',
    'BRECOS',
    'Calvin Klein',
    'CAPRICE',
    'CESARE PACIOTTI',
    'CRISTIAN DIOR',
    'СESANO BOSCONE',
    'CHANEL',
    'COACH',
    'COLUMBIA',
    'CAMPER',
    'CELINE',
    'CONVERSE',
    'CAT',
    'CASADEI',
    'CROMIA',
    'COCCINELLE',
    'CARLO PIGNATELLI',
    'CLARKS',
    'CHARGED',
    'CARLO PAZOLINI',
    'CARNERY',
    'Conhpol',
    'CROCS',
    'CONVERSE',
    'CARNABY',
    'CARLO PACHINI',
    'CHRISTOPHE AUBER',
    'CAOVILLA',
    'COSTA',
    'DIESEL',
    'DKNY',
    'DOLCE GABBANA',
    'DSQUARED2',
    'DOUCALS',
    'DEMOCRATA',
    'Disco Rosso',
    'Dino Bigioni',
    'ELISABETTA FRANCHI',
    'ESTRO',
    'ELEGANCI',
    'ESSE',
    'Ermenegildo Zegna',
    'EYTYS',
    'ERIKA',
    'ENTENSA',
    'ECKSE',
    'ESSERE',
    'ERMANNO scervino',
    'EMPORIO ARMANI',
    'EMPRESS',
    'ETRO',
    'FERRAGAMO',
    'FABI',
    'FELLINI',
    'Frelly Woman',
    'FRATELLI ROSSETTI',
    'FABIO MONELLI',
    'FЕNDI',
    'FRANKIE MORELLO',
    'FABIO RUSCONI',
    'FURLA',
    'FERRARI',
    'FRU',
    'FABIANA FILIPPI',
    'Francesco RUSSO',
    'GIARDINI',
    'GORDON BROS',
    'giampieronicola',
    'GIUSEPPE ZANOTI',
    'GIANVITO ROSSI',
    'GIORGIO FABIANI',
    'GUCCI',
    'GANT',
    'GIANNI RENZI',
    'GEOX',
    'GUESS',
    'GIVENCHY',
    'GIOVANNI CICCIOLI',
    'GERARDINA dimaggio',
    'GAS',
    'GREYDER',
    'GIANI',
    'GGDB',
    'GRATUDE',
    'GIANNI NOTARO',
    'GABOR',
    'GIAMPAOLO VIOZZI',
    'GIANNA MELIANI',
    'GIOVANNI FABIANI',
    'GALERIES Lafayette',
    'GORDON BROS',
    'GUGLIELMO ROTTA',
    'GUERO',
    'HELENA SORETTI',
    'HELEN MARLEN',
    'HERMES',
    'HENDERSON',
    'HUGO BOSS',
    'HALMANERA',
    'HELLY HANSEN',
    'HOGL',
    'HOGAN',
    'HORTON',
    'High Soft',
    'hoka',
    'HEREU',
    'НМ',
    'ISABEL MARANT',
    'ICEBERG',
    'Ice Play',
    'IREN VARTIK',
    'ISAIA',
    'INCH2',
    'IDEAL SHOES',
    'ILVI',
    'IKOS',
    'IRO',
    'JIMMY CHOO',
    'JANS',
    'JORDAN',
    'JACQUEMUS',
    'JADIOR',
    'JILSANDER',
    'JOMA',
    'JEANNOT',
    'JOHN VARVATOS',
    'JULIA KAZAKOVA',
    'JOPP',
    'JOHN GALLIANO',
    'JECOME',
    'JW PEI',
    'KITON',
    'KELTON',
    'KOCHOROVSKA',
    'KOALABI',
    'KAZAR',
    'KAREN MILLEN',
    'Karl Logerfeld',
    'KITE',
    'KURT GEIGER',
    'KENDALL+KYLIE',
    'KOHANI',
    'KOS',
    'Lido Marinozzi',
    'LANVIN',
    'LORО PIANА',
    'LESILLA',
    'LOUIS VUITTON',
    'LAURA BELLARIVA',
    'LESTA',
    'LLOYD',
    'LACOSTE',
    'LOUBOUTINS',
    'L~AUTRB CHOSE',
    'LORIBLU',
    'L"CARVARI',
    'LOVE MOSCHINO',
    'LVAN',
    'LIU*JO',
    'LEVIS',
    'LUCIANO CARVARI',
    'LAB',
    'LORETTA',
    'l\'atelier du sac',
    'LOEWE',
    'LAURA BIAGIOTTI',
    'LOWA',
    'MIRATON',
    'MAX MARA',
    'MICHAEL KORS',
    'MALETSKIY',
    'MARCCAIN',
    'MARNI',
    'MASSIMO DUTTI',
    'MIRATON',
    'MARZETTI',
    'MG Boys',
    'MARCO POLO',
    'MIGUEL MIRATEZ',
    'Marino Blasi',
    'MORESCHI',
    'miu miu',
    'MOON BOOT',
    'MICHAEL STONE',
    'MAISON MARGIELA',
    'MARINO FABIANI',
    'MARIO BRUNI',
    'Mia May',
    'MARC JACOBS',
    'MERRELL',
    'MARRCO TOZZI',
    'MEXX',
    'MNG',
    'MIRKO CICCIOLI',
    'MANDELLI',
    'ME.MORA',
    'MONCLER',
    'MARIO MORO',
    'MUNICH',
    'MAX .CO',
    'MISS SIXTY',
    'MOSCHINO',
    'Micholas Kirkwood',
    'MIRKO',
    'MAGZA',
    'MACCIONI',
    'MACH MACH',
    'MELLY',
    'NEW HOLLAND',
    'NIKE',
    'NEW BALANCE',
    'NURSACE',
    'NEXT',
    'Nicolas kirkwood',
    'NAKED WOLFE',
    'Napoleoni',
    'Nomade',
    'NANDO MUZI',
    'NORMAJ.BAKER',
    'Nero GIARDINI',
    'Nila and Nila',
    'NINE WEST',
    'OFF-WHITE',
    'OYSHO',
    'POLANN',
    'PINKO',
    'PESERICO',
    'Pacciotti',
    'PATRIZIA PEPE',
    'PELLETTIERI DI PARMA',
    'PERTINI',
    'POLLINI',
    'PREPPY',
    'PREMIATA',
    'PUMA',
    'PHILIPP PLEIN',
    'PEPE JESTA',
    'PRADA',
    'PRPY',
    'Picolinos',
    'PAKERSON',
    'PARIS TEXAS',
    'PRIMARK',
    'Pierre Cardin',
    'PAUL SHARK',
    'PAZOLINI',
    'PETER KAIZER',
    'PHILLIP HARDY',
    'PROENZA Schouler',
    'REPLAY',
    'RIEKER',
    'REMONTE',
    'RIZZANO',
    'REEBOK',
    'RENE CFOVILLA',
    'ROMASHKA',
    'REN VARTIK',
    'RICHMOND',
    'ROBERTO CAVALLI',
    'RONDO',
    'RESPECT',
    'RENZI',
    'REPO',
    'ROY ROBSON',
    'RALPH LOUREN',
    'SCHUTZ',
    'SANTONI',
    'Santoro G',
    'SKECHERS',
    'SAINT LOURENT',
    'STEFANO RICCI',
    'SERGIO ROSSI',
    'SAMSONITE',
    'STUART WEITZMAN',
    'SERCIO MANCHOT',
    'SWISS ENGINEERING',
    'SEKADA',
    'STOKTON',
    'SAM EDELMAN',
    'SAUCONY',
    'Salvatore Ferragamo',
    'STUDIO 27',
    'SG2R',
    'SERGIO MANCHOT',
    'SPORTMAX',
    'SANDRO',
    'STEVE MADDEN',
    'Stella McCartney',
    'SERGIO LEVANTESI',
    'STEFFEN SCHRAUT',
    'STEMAR',
    'SASHA FABIANI',
    'SOFIA BALDI',
    'STEMAR',
    'Stradivarius',
    'SOLANA',
    'STEFANIA',
    'TJ COLLECTION',
    'TONI SABATINI',
    'Tomaris',
    'TWINSET',
    'TODS',
    'TOM TAILOR',
    'TIMBERLAND',
    'TOMMY HILFIGER',
    'TOM FORD',
    'Tabitha Simmons',
    'TOMMY JEANS',
    'THE NORTH FACE',
    'toteme',
    'TRUSSARDI',
    'THE ROW',
    'TED BAKER',
    'TORY BURCH',
    'THE ATTICO',
    'TIFFI',
    'te shoes kyiv',
    'UTERQUE',
    'UNDER ARMOUR',
    'UGG',
    'UQ',
    'U.S POLO',
    'URSACE',
    'V.I.KONTY',
    'VERSACE',
    'VAGABOND',
    'Vittorio Virgili',
    'VALENTINO',
    'VAB',
    'VANS',
    'VIC MATIE',
    'VOILE BLANCHE',
    'VITTO ROSSI',
    'VIF',
    'VERA PELLE',
    'VALENTINO',
    'VIRIER',
    'WEEKEND',
    'WINDPROOF',
    'WANDERSON',
    'WITTCHEN',
    'WELFARE',
    'WONDERS',
    'WINDSORSMITH',
    'YONEX',
    'YVES SAINT LAURENT',
    'ZARA',
    'Zoro Piana',
    'ZEGNA',
    'ZILLI'
];

async function main() {
    console.log(`Starting seed for ${brandList.length} brands...`);
    let count = 0;

    for (const item of brandList) {
        const formatted = item.trim();

        const existing = await prisma.referenceItem.findFirst({
            where: { type: 'BRAND', value: formatted }
        });

        if (!existing) {
            await prisma.referenceItem.create({
                data: {
                    type: 'BRAND',
                    value: formatted
                }
            });
            count++;
        }
    }
    console.log(`Successfully added ${count} new brands.`);
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
